"use client"

import { Montserrat, Playfair_Display } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "./context/userContext";

const montserrat = Montserrat({
  variable:"--font-montserrat",
  subsets:["cyrillic","latin"],
  weight:["100","200","300","400","500","600","700","800","900"]
});

const playfair = Playfair_Display({
  variable: "--font-playfair",
  subsets:["cyrillic","latin"],
  weight: ["400","500","600","700","800","900"]
})

// export const metadata = {
//   title: "Florette - Доставка цветов в Красноярске",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="ru">
    <title>Florette - Доставка цветов в Красноярске</title>
      <body
        className={` ${montserrat.variable}  antialiased bg-[#5B635C]`}
      >
        <AuthProvider>
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
